"""suggestions

Revision ID: 4046b2394811
Revises: b255fdf52cb4
Create Date: 2026-10-04 17:10:31.055089

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4046b2394811"
down_revision: str | Sequence[str] | None = "b255fdf52cb4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "suggestions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("anchor_start", sa.Integer(), nullable=True),
        sa.Column("anchor_end", sa.Integer(), nullable=True),
        sa.Column("paragraph_id", sa.String(length=100), nullable=True),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column("replacement", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("honeypot", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("spam_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_suggestions_post_id"), "suggestions", ["post_id"], unique=False)
    op.create_index(op.f("ix_suggestions_status"), "suggestions", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_suggestions_status"), table_name="suggestions")
    op.drop_index(op.f("ix_suggestions_post_id"), table_name="suggestions")
    op.drop_table("suggestions")
    # ### end Alembic commands ###
