"""posts and post_revisions

Revision ID: b255fdf52cb4
Revises: afad6ea87a2a
Create Date: 2026-10-04 16:52:54.172695

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b255fdf52cb4"
down_revision: str | Sequence[str] | None = "afad6ea87a2a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_posts_slug"), "posts", ["slug"], unique=True)
    op.create_table(
        "post_revisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("credit_name", sa.String(length=100), nullable=True),
        sa.Column("change_start", sa.Integer(), nullable=True),
        sa.Column("change_end", sa.Integer(), nullable=True),
        sa.Column("previous_text", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("post_id", "number"),
    )
    op.create_index(op.f("ix_post_revisions_post_id"), "post_revisions", ["post_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_post_revisions_post_id"), table_name="post_revisions")
    op.drop_table("post_revisions")
    op.drop_index(op.f("ix_posts_slug"), table_name="posts")
    op.drop_table("posts")
    # ### end Alembic commands ###
